version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"  # Allow port configuration via environment variable
    environment:
      - MONGODB_URI=mongodb://mongo:27017/taskmanager
      - PORT=3000
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network
    # Not exposed to host - only accessible within Docker network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge 